In [3]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("exercises.csv")

In [8]:
df.head()

,id,name_en,name_de,name_es,category,force_type,mechanic,difficulty,equipment,body_part,...,tags,met,is_unilateral,is_bodyweight,description_en,instructions_en,image_classic_start,image_classic_peak,image_flat_start,image_flat_peak
0,arnold-press,Arnold Press,Arnold Press,Press Arnold,strength,push,compound,intermediate,dumbbell,chest,...,knee_safe|lower_back_safe|no_axial_load,6.0,False,False,An overhead press variation rotating the palms...,Hold a pair of dumbbells at shoulder height wi...,images/classic/arnold-press-start.webp,images/classic/arnold-press-peak.webp,images/flat/arnold-press-start.webp,images/flat/arnold-press-peak.webp
1,banded-lateral-walk,Banded Lateral Walk,Lateral Walk mit Band,Caminata Lateral con Banda,strength,dynamic,compound,beginner,loop_band,upper_legs,...,leg_day|warmup,6.0,False,False,A side-stepping movement performed with a loop...,Place a loop band around the legs above the kn...,images/classic/banded-lateral-walk-start.webp,images/classic/banded-lateral-walk-peak.webp,images/flat/banded-lateral-walk-start.webp,images/flat/banded-lateral-walk-peak.webp
2,barbell-glute-bridge,Barbell Glute Bridge,Langhantel-Gesäßbrücke,Puente de Glúteos con Barra,strength,push,compound,intermediate,barbell,upper_legs,...,leg_day|lower_back_safe|knee_safe|shoulder_saf...,6.0,False,False,A weighted glute bridge using a barbell for in...,Lie on the floor with a barbell across your hi...,images/classic/barbell-glute-bridge-start.webp,images/classic/barbell-glute-bridge-peak.webp,images/flat/barbell-glute-bridge-start.webp,images/flat/barbell-glute-bridge-peak.webp
3,behind-the-back-barbell-shrug,Behind the Back Barbell Shrug,Langhantel-Shrug hinter dem Rücken,Encogimiento de Hombros con Barra Detrás de la...,strength,pull,isolation,intermediate,barbell,back,...,knee_safe|lower_back_safe|shoulder_safe|no_axi...,5.0,False,False,A shrug variation with the barbell held behind...,Stand holding a barbell behind your back with ...,images/classic/behind-the-back-barbell-shrug-s...,images/classic/behind-the-back-barbell-shrug-p...,images/flat/behind-the-back-barbell-shrug-star...,images/flat/behind-the-back-barbell-shrug-peak...
4,behind-the-neck-press,Behind the Neck Press,Nackendrücken,Press Detrás del Cuello,strength,push,compound,intermediate,barbell,chest,...,knee_safe,6.0,False,False,An overhead press performed with the barbell s...,Sit or stand with a barbell resting on your up...,images/classic/behind-the-neck-press-start.webp,images/classic/behind-the-neck-press-peak.webp,images/flat/behind-the-neck-press-start.webp,images/flat/behind-the-neck-press-peak.webp

In [9]:
df.tail()

,id,name_en,name_de,name_es,category,force_type,mechanic,difficulty,equipment,body_part,...,tags,met,is_unilateral,is_bodyweight,description_en,instructions_en,image_classic_start,image_classic_peak,image_flat_start,image_flat_peak
16,pec-deck,Pec Deck,Pec Deck,Pec Deck,strength,push,isolation,beginner,pec_deck,chest,...,push_day|knee_safe|no_axial_load|lower_back_sa...,5.0,False,False,A chest isolation machine with fixed elbow pad...,Sit in the pec deck machine and place your for...,images/classic/pec-deck-start.webp,images/classic/pec-deck-peak.webp,images/flat/pec-deck-start.webp,images/flat/pec-deck-peak.webp
17,push-press,Push Press,Push Press,Press de Empuje,strength,push,compound,intermediate,barbell,shoulders,...,push_day|knee_safe,6.0,False,False,A barbell overhead press using leg drive to pr...,Stand with a barbell racked on your front delt...,images/classic/push-press-start.webp,images/classic/push-press-peak.webp,images/flat/push-press-start.webp,images/flat/push-press-peak.webp
18,smith-machine-bent-over-row,Smith Machine Bent Over Row,Smith Machine Bent Over Row,Remo Inclinado en Máquina Smith,strength,pull,compound,beginner,smith_machine,back,...,knee_safe|shoulder_safe,6.0,False,False,"A bent-over row in the Smith machine, with a f...",Stand inside a Smith machine with feet shoulde...,images/classic/smith-machine-bent-over-row-sta...,images/classic/smith-machine-bent-over-row-pea...,images/flat/smith-machine-bent-over-row-start....,images/flat/smith-machine-bent-over-row-peak.webp
19,smith-machine-squat,Smith Machine Squat,Smith-Maschine Kniebeuge,Sentadilla en Máquina Smith,strength,push,compound,beginner,smith_machine,upper_legs,...,NaN,6.0,False,False,"A squat performed on the Smith machine, using ...",Set the Smith machine bar at shoulder height a...,images/classic/smith-machine-squat-start.webp,images/classic/smith-machine-squat-peak.webp,images/flat/smith-machine-squat-start.webp,images/flat/smith-machine-squat-peak.webp
20,wide-grip-seated-cable-row,Wide Grip Seated Cable Row,Sitzrudern mit breitem Griff am Kabelzug,Remo en Polea Sentado en Agarre Ancho,strength,pull,compound,intermediate,cable,back,...,pull_day|knee_safe|no_axial_load|lower_back_sa...,6.0,False,False,A seated rowing variation with a wide grip emp...,Sit at a cable row station with feet on the pl...,images/classic/wide-grip-seated-cable-row-star...,images/classic/wide-grip-seated-cable-row-peak...,images/flat/wide-grip-seated-cable-row-start.webp,images/flat/wide-grip-seated-cable-row-peak.webp

In [10]:
df.shape

(21, 23)

In [12]:
df.columns

Index(['id', 'name_en', 'name_de', 'name_es', 'category', 'force_type',
       'mechanic', 'difficulty', 'equipment', 'body_part', 'primary_muscles',
       'secondary_muscles', 'goals', 'tags', 'met', 'is_unilateral',
       'is_bodyweight', 'description_en', 'instructions_en',
       'image_classic_start', 'image_classic_peak', 'image_flat_start',
       'image_flat_peak'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   21 non-null     str
 1   name_en              21 non-null     str
 2   name_de              21 non-null     str
 3   name_es              21 non-null     str
 4   category             21 non-null     str
 5   force_type           21 non-null     str
 6   mechanic             21 non-null     str
 7   difficulty           21 non-null     str
 8   equipment            20 non-null     str
 9   body_part            21 non-null     str
 10  primary_muscles      21 non-null     str
 11  secondary_muscles    20 non-null     str
 12  goals                21 non-null     str
 13  tags                 20 non-null     str
 14  met                  21 non-null     float64
 15  is_unilateral        21 non-null     bool
 16  is_bodyweight        21 non-null     bool
 17  description_en       21 non-null     str
 18  instructions_en      21 non-null     str
 19  image_classic_start  21 non-null     str
 20  image_classic_peak   21 non-null     str
 21  image_flat_start     21 non-null     str
 22  image_flat_peak      21 non-null     str
dtypes: bool(2), float64(1), str(20)
memory usage: 3.6 KB

In [15]:
df.describe()

             met
count  21.000000
mean    5.714286
std     0.462910
min     5.000000
25%     5.000000
50%     6.000000
75%     6.000000
max     6.000000

In [18]:
df.dtypes

id                         str
name_en                    str
name_de                    str
name_es                    str
category                   str
force_type                 str
mechanic                   str
difficulty                 str
equipment                  str
body_part                  str
primary_muscles            str
secondary_muscles          str
goals                      str
tags                       str
met                    float64
is_unilateral             bool
is_bodyweight             bool
description_en             str
instructions_en            str
image_classic_start        str
image_classic_peak         str
image_flat_start           str
image_flat_peak            str
dtype: object

In [19]:
df.isnull().sum()

id                     0
name_en                0
name_de                0
name_es                0
category               0
force_type             0
mechanic               0
difficulty             0
equipment              1
body_part              0
primary_muscles        0
secondary_muscles      1
goals                  0
tags                   1
met                    0
is_unilateral          0
is_bodyweight          0
description_en         0
instructions_en        0
image_classic_start    0
image_classic_peak     0
image_flat_start       0
image_flat_peak        0
dtype: int64

In [20]:
df.nunique()

id                     21
name_en                21
name_de                21
name_es                21
category                1
force_type              3
mechanic                2
difficulty              2
equipment               8
body_part               7
primary_muscles        13
secondary_muscles      18
goals                   4
tags                   18
met                     2
is_unilateral           2
is_bodyweight           2
description_en         21
instructions_en        21
image_classic_start    21
image_classic_peak     21
image_flat_start       21
image_flat_peak        21
dtype: int64

In [22]:
df.sample(8)

,id,name_en,name_de,name_es,category,force_type,mechanic,difficulty,equipment,body_part,...,tags,met,is_unilateral,is_bodyweight,description_en,instructions_en,image_classic_start,image_classic_peak,image_flat_start,image_flat_peak
20,wide-grip-seated-cable-row,Wide Grip Seated Cable Row,Sitzrudern mit breitem Griff am Kabelzug,Remo en Polea Sentado en Agarre Ancho,strength,pull,compound,intermediate,cable,back,...,pull_day|knee_safe|no_axial_load|lower_back_sa...,6.0,False,False,A seated rowing variation with a wide grip emp...,Sit at a cable row station with feet on the pl...,images/classic/wide-grip-seated-cable-row-star...,images/classic/wide-grip-seated-cable-row-peak...,images/flat/wide-grip-seated-cable-row-start.webp,images/flat/wide-grip-seated-cable-row-peak.webp
10,double-kettlebell-row,Double Kettlebell Row,Double Kettlebell Rudern,Remo con Dos Pesas Rusas,strength,pull,compound,intermediate,kettlebell,back,...,knee_safe|lower_back_safe|shoulder_safe|no_axi...,6.0,False,False,A bent-over rowing exercise pulling two kettle...,Hold a kettlebell in each hand and hinge forwa...,images/classic/double-kettlebell-row-start.webp,images/classic/double-kettlebell-row-peak.webp,images/flat/double-kettlebell-row-start.webp,images/flat/double-kettlebell-row-peak.webp
19,smith-machine-squat,Smith Machine Squat,Smith-Maschine Kniebeuge,Sentadilla en Máquina Smith,strength,push,compound,beginner,smith_machine,upper_legs,...,NaN,6.0,False,False,"A squat performed on the Smith machine, using ...",Set the Smith machine bar at shoulder height a...,images/classic/smith-machine-squat-start.webp,images/classic/smith-machine-squat-peak.webp,images/flat/smith-machine-squat-start.webp,images/flat/smith-machine-squat-peak.webp
1,banded-lateral-walk,Banded Lateral Walk,Lateral Walk mit Band,Caminata Lateral con Banda,strength,dynamic,compound,beginner,loop_band,upper_legs,...,leg_day|warmup,6.0,False,False,A side-stepping movement performed with a loop...,Place a loop band around the legs above the kn...,images/classic/banded-lateral-walk-start.webp,images/classic/banded-lateral-walk-peak.webp,images/flat/banded-lateral-walk-start.webp,images/flat/banded-lateral-walk-peak.webp
13,floor-kettlebell-pullover,Floor Kettlebell Pullover,Boden Kettlebell Pullover,Pullover con Pesa Rusa en Suelo,strength,pull,compound,beginner,kettlebell,back,...,pull_day,6.0,False,False,A pullover done lying on the floor with a kett...,Lie face-up on the floor with knees bent and f...,images/classic/floor-kettlebell-pullover-start...,images/classic/floor-kettlebell-pullover-peak....,images/flat/floor-kettlebell-pullover-start.webp,images/flat/floor-kettlebell-pullover-peak.webp
9,cable-external-rotation,Cable External Rotation,Kabelzug Außenrotation,Rotación Externa con Cable,strength,push,compound,intermediate,cable,shoulders,...,knee_safe|no_axial_load|lower_back_safe|should...,6.0,False,False,A cable exercise rotating the forearm outward ...,Set a cable pulley to elbow height and grip th...,images/classic/cable-external-rotation-start.webp,images/classic/cable-external-rotation-peak.webp,images/flat/cable-external-rotation-start.webp,images/flat/cable-external-rotation-peak.webp
3,behind-the-back-barbell-shrug,Behind the Back Barbell Shrug,Langhantel-Shrug hinter dem Rücken,Encogimiento de Hombros con Barra Detrás de la...,strength,pull,isolation,intermediate,barbell,back,...,knee_safe|lower_back_safe|shoulder_safe|no_axi...,5.0,False,False,A shrug variation with the barbell held behind...,Stand holding a barbell behind your back with ...,images/classic/behind-the-back-barbell-shrug-s...,images/classic/behind-the-back-barbell-shrug-p...,images/flat/behind-the-back-barbell-shrug-star...,images/flat/behind-the-back-barbell-shrug-peak...
5,bench-dips,Bench Dips,Bank-Dips,Fondos en Banco,strength,push,compound,intermediate,NaN,upper_arms,...,knee_safe|no_axial_load|lower_back_safe|requir...,5.0,False,True,A bodyweight pressing movement with hands on a...,Sit on a bench and place your hands on the edg...,images/classic/bench-dips-start.webp,images/classic/bench-dips-peak.webp,images/flat/bench-dips-start.webp,images/flat/bench-dips-peak.webp

In [26]:
df.value_counts()

id                             name_en                        name_de                                   name_es                                                 category  force_type  mechanic   difficulty    equipment      body_part   primary_muscles                            secondary_muscles                                    goals                                 tags                                                                met  is_unilateral  is_bodyweight  description_en                                                                                                                                                                                                                             instructions_en                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     image_classic_start                                      image_classic_peak                                      image_flat_start                                      image_flat_peak
arnold-press                   Arnold Press                   Arnold Press                              Press Arnold                                            strength  push        compound   intermediate  dumbbell       chest       anterior_deltoid|lateral_deltoid           serratus_anterior|trapezius|triceps_brachii          hypertrophy|strength                  knee_safe|lower_back_safe|no_axial_load                             6.0  False          False          An overhead press variation rotating the palms from facing the body to facing forward, working the front and side deltoids.                                                                                                                Hold a pair of dumbbells at shoulder height with palms facing you. | Press the dumbbells overhead while rotating your palms to face forward. | Fully extend your arms at the top without locking the elbows. | Reverse the motion and rotate back to the start. | Repeat for the desired number of reps.                                                                                                                                                                                                                                            images/classic/arnold-press-start.webp                   images/classic/arnold-press-peak.webp                   images/flat/arnold-press-start.webp                   images/flat/arnold-press-peak.webp                     1
banded-lateral-walk            Banded Lateral Walk            Lateral Walk mit Band                     Caminata Lateral con Banda                              strength  dynamic     compound   beginner      loop_band      upper_legs  gluteus_medius                             gluteus_maximus|quadriceps                           rehabilitation|endurance|hypertrophy  leg_day|warmup                                                      6.0  False          False          A side-stepping movement performed with a loop band wrapped above the knees or around the ankles. Constant abduction tension fires the gluteus medius — a staple warm-up and rehab drill for hip stability.                                Place a loop band around the legs above the knees (or around the ankles for a harder version). | Stand in a quarter-squat: feet shoulder-width, hips back, chest up, knees tracking over the toes. | Step one foot directly out to the side against the band tension. | Bring the trailing foot in toward the lead — keep tension on the band the entire time, do not let the feet snap together. | Continue side-stepping in one direction for the prescribed reps or distance, then reverse. | Stay low throughout; do not pop up between steps.  images/classic/banded-lateral-walk-start.webp            images/classic/banded-lateral-walk-peak.webp            images/flat/banded-lateral-walk-start.webp            images/flat/banded-lateral-walk-peak.webp              1
barbell-glute-bridge           Barbell Glute Bridge           Langhantel-Gesäßbrücke                    Puente de Glúteos con Barra                             strength  push        compound   intermediate  barbell        upper_legs  gluteus_maximus                            hamstrings                                           hypertrophy|strength                  leg_day|lower_back_safe|knee_safe|shoulder_safe|no_axial_load       6.0  False          False          A weighted glute bridge using a barbell for increased resistance.                                                                                                                                                                          Lie on the floor with a barbell across your hips and knees bent. | Drive your hips up by squeezing your glutes. | Hold at the top with hips fully extended. | Lower with control. | Repeat.                                                                                                                                                                                                                                                                                                                                                         images/classic/barbell-glute-bridge-start.webp           images/classic/barbell-glute-bridge-peak.webp           images/flat/barbell-glute-bridge-start.webp           images/flat/barbell-glute-bridge-peak.webp             1
behind-the-back-barbell-shrug  Behind the Back Barbell Shrug  Langhantel-Shrug hinter dem Rücken        Encogimiento de Hombros con Barra Detrás de la Espalda  strength  pull        isolation  intermediate  barbell        back        trapezius                                  forearm_flexors|rhomboids                            hypertrophy                           knee_safe|lower_back_safe|shoulder_safe|no_axial_load               5.0  False          False          A shrug variation with the barbell held behind the body, targeting the trapezius.                                                                                                                                                          Stand holding a barbell behind your back with an overhand grip. | Keep your arms straight and chest up. | Shrug your shoulders straight up toward your ears. | Pause and squeeze at the top. | Lower under control and repeat.                                                                                                                                                                                                                                                                                                                      images/classic/behind-the-back-barbell-shrug-start.webp  images/classic/behind-the-back-barbell-shrug-peak.webp  images/flat/behind-the-back-barbell-shrug-start.webp  images/flat/behind-the-back-barbell-shrug-peak.webp    1
behind-the-neck-press          Behind the Neck Press          Nackendrücken                             Press Detrás del Cuello                                 strength  push        compound   intermediate  barbell        chest       anterior_deltoid|lateral_deltoid           trapezius|triceps_brachii                            hypertrophy|strength                  knee_safe                                                           6.0  False          False          An overhead press performed with the barbell starting behind the neck, emphasizing the front and side deltoids.                                                                                                                            Sit or stand with a barbell resting on your upper traps behind your neck. | Grip the bar wider than shoulder width. | Press the bar straight up overhead until your arms are extended. | Lower the bar back to the starting position under control. | Repeat for the desired number of reps.                                                                                                                                                                                                                                                        images/classic/behind-the-neck-press-start.webp          images/classic/behind-the-neck-press-peak.webp          images/flat/behind-the-neck-press-start.webp          images/flat/behind-the-neck-press-peak.webp            1
bent-arm-ez-bar-pullover       Bent-Arm EZ-Bar Pullover       SZ-Stangen-Pullover mit gebeugten Armen   Pullover con Barra Z y Brazos Flexionados               strength  pull        compound   intermediate  ez_bar         back        latissimus_dorsi|pectoralis_major          posterior_deltoid|serratus_anterior|triceps_brachii  hypertrophy|strength                  pull_day|requires_bench                                             6.0  False          False          A bent-arm pullover on a flat bench using an EZ-bar — wrist-friendlier than the straight barbell version while keeping the deep lat and pec stretch.                                                                                       Lie on a flat bench holding an EZ-bar with a narrow overhand grip on the inner bends. | Start with the bar above your chest, elbows bent to roughly 90 degrees. | Keep the elbow angle fixed and lower the bar back in an arc overhead until a deep stretch is felt in the lats and pecs. | Pull the bar back over the chest along the same arc, without straightening the elbows. | Repeat for the recommended number of repetitions.                                                                                                              images/classic/bent-arm-ez-bar-pullover-start.webp       images/classic/bent-arm-ez-bar-pullover-peak.webp       images/flat/bent-arm-ez-bar-pullover-start.webp       images/flat/bent-arm-ez-bar-pullover-peak.webp         1
bulgarian-split-squat          Bulgarian Split Squat          Bulgarische Kniebeuge                     Sentadilla Búlgara                                      strength  push        compound   intermediate  dumbbell       upper_legs  gluteus_maximus|quadriceps                 hamstrings                                           hypertrophy|strength                  leg_day|shoulder_safe|lower_back_safe|no_axial_load|requires_bench  6.0  True           False          A single-leg squat variation with the rear foot elevated.                                                                                                                                                                                  Stand in front of a bench, place one foot behind you on the bench. | Hold dumbbells at your sides. | Lower your body until your front thigh is parallel to the floor. | Push through your front heel to stand back up. | Repeat on both sides.                                                                                                                                                                                                                                                                                                      images/classic/bulgarian-split-squat-start.webp          images/classic/bulgarian-split-squat-peak.webp          images/flat/bulgarian-split-squat-start.webp          images/flat/bulgarian-split-squat-peak.webp            1
cable-crunch                   Cable Crunch                   Kabelzug Crunch                           Crunch con Cable                                        strength  push        isolation  intermediate  cable          core        rectus_abdominis                           obliques|transverse_abdominis                        hypertrophy                           lower_back_safe|knee_safe|shoulder_safe|no_axial_load               5.0  False          False          A kneeling abdominal exercise flexing the spine against cable resistance, allowing progressive loading of the rectus abdominis.                                                                                                            Kneel in front of a cable machine with a rope attachment at the top. | Hold the rope near your forehead with elbows bent. | Crunch down by flexing your spine and bringing your elbows to your thighs. | Squeeze your abs hard at the bottom. | Return to the start position and repeat.                                                                                                                                                                                                                                                            images/classic/cable-crunch-start.webp                   images/classic/cable-crunch-peak.webp                   images/flat/cable-crunch-start.webp                   images/flat/cable-crunch-peak.webp                     1
cable-external-rotation        Cable External Rotation        Kabelzug Außenrotation                    Rotación Externa con Cable                              strength  push        compound   intermediate  cable          shoulders   posterior_deltoid                          rhomboids|trapezius                                  hypertrophy|strength                  knee_safe|no_axial_load|lower_back_safe|shoulder_safe               6.0  False          False          A cable exercise rotating the forearm outward with the elbow pinned at the side, strengthening the rear delts.                                                                                                                             Set a cable pulley to elbow height and grip the handle. | Stand side-on to the machine with your working elbow bent at 90 degrees. | Keep your elbow glued to your side and rotate your forearm outward. | Pause at the end of the movement. | Return under control. Complete reps on one side, then switch.                                                                                                                                                                                                                                        images/classic/cable-external-rotation-start.webp        images/classic/cable-external-rotation-peak.webp        images/flat/cable-external-rotation-start.webp        images/flat/cable-external-rotation-peak.webp          1
double-kettlebell-row          Double Kettlebell Row          Double Kettlebell Rudern                  Remo con Dos Pesas Rusas                                strength  pull        compound   intermediate  kettlebell     back        latissimus_dorsi|rhomboids                 biceps_brachii|erector_spinae|trapezius              hypertrophy|strength                  knee_safe|lower_back_safe|shoulder_safe|no_axial_load               6.0  False          False          A bent-over rowing exercise pulling two kettlebells to the hips, strengthening the lats and upper back.                                                                                                                                    Hold a kettlebell in each hand and hinge forward at the hips. | Let your arms hang straight down from your shoulders. | Row both kettlebells to your hips by driving elbows back. | Squeeze your shoulder blades at the top. | Lower under control and repeat.                                                                                                                                                                                                                                                                                      images/classic/double-kettlebell-row-start.webp          images/classic/double-kettlebell-row-peak.webp          images/flat/double-kettlebell-row-start.webp          images/flat/double-kettlebell-row-peak.webp            1
dumbbell-calf-raise            Dumbbell Calf Raise            Kurzhantel Wadenheben                     Elevación de Talones con Mancuernas                     strength  push        isolation  intermediate  dumbbell       lower_legs  gastrocnemius|soleus                       forearm_flexors                                      hypertrophy                           knee_safe|shoulder_safe|lower_back_safe|no_axial_load               5.0  False          False          A weighted calf raise holding dumbbells at the sides, performed on an elevated edge for a full stretch.                                                                                                                                    Stand holding a dumbbell in each hand at your sides. | Place the balls of your feet on a raised surface with heels hanging off. | Press through the balls of your feet to raise your heels as high as possible. | Squeeze your calves at the top of the movement. | Lower your heels below the platform to stretch the calves. | Repeat for the desired number of reps.                                                                                                                                                                             images/classic/dumbbell-calf-raise-start.webp            images/classic/dumbbell-calf-raise-peak.webp            images/flat/dumbbell-calf-raise-start.webp            images/flat/dumbbell-calf-raise-peak.webp              1
floor-kettlebell-pullover      Floor Kettlebell Pullover      Boden Kettlebell Pullover                 Pullover con Pesa Rusa en Suelo                         strength  pull        compound   beginner      kettlebell     back        latissimus_dorsi|pectoralis_major          serratus_anterior|triceps_brachii                    hypertrophy                           pull_day                                                            6.0  False          False          A pullover done lying on the floor with a kettlebell held by the handle or by the horns. The floor limits the range of motion compared to the bench version, which reduces shoulder strain and makes it a good home-gym or prehab option.  Lie face-up on the floor with knees bent and feet flat. | Hold a kettlebell by the handle with both hands above your chest, arms almost straight (slight elbow bend). | Keeping the elbow angle fixed, lower the bell overhead in an arc until the upper arms touch the floor. | Pull the bell back above the chest along the same arc. | Repeat for the recommended number of repetitions.                                                                                                                                                         images/classic/floor-kettlebell-pullover-start.webp      images/classic/floor-kettlebell-pullover-peak.webp      images/flat/floor-kettlebell-pullover-start.webp      images/flat/floor-kettlebell-pullover-peak.webp        1